version: '3'
networks:
  todo_network_uat:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "208.13.17.8/17"
services:
  api_todo:
    container_name: "todo_uat"
    image: "node:16.14.0"
    networks:
      - todo_network_uat
    restart: always
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    env_file:
      - .env
    ports:
      - 7030:8080
    command: bash -c "npm install && node index.js"